import Header from '../../components/layout/Header.jsx';
import Footer from '../../components/layout/Footer.jsx';
import Button from '../../components/ui/Button.jsx';
import Card from '../../components/ui/Card.jsx';
import { dataModel, pricingPlans } from '../../data/pisaData.js';

const pillars = ['AI Individual Development Plans', 'Weekly Training Plans', 'College Recruiting CRM', 'Parent + Coach Reports', 'Role-Based Dashboards', 'Stripe-Ready Payments'];
const roles = ['Coach', 'Player', 'Parent', 'Director', 'Staff'];
const extensions = ['Prohub', 'Prolens', 'Scouting App', 'College Recruitment', 'Training App'];

export default function Home() {
  return <><Header /><main><section className="hero section-pad"><div className="hero-content"><p className="eyebrow">ProHub • Premium soccer SaaS platform</p><h1>Run your soccer organization from one connected ProHub workspace.</h1><p className="hero-copy">ProHub by Stout Media Group connects PISA / Protouch-style academies, clubs, schools, coaches, players, and parents with dashboards, rosters, session plans, IDPs, reports, messages, and billing-ready onboarding.</p><div className="hero-actions"><Button to="/register">Start ProHub</Button><Button to="/pricing" variant="secondary">View pricing</Button></div><div className="tag-list">{extensions.map((item) => <span key={item}>{item}-ready</span>)}</div></div><aside className="hero-panel card glow-card"><div className="metric-row"><span>AI plan completion</span><strong>76%</strong></div><div className="metric-row"><span>Recruiting pipeline</span><strong>18 schools</strong></div><div className="metric-row"><span>Monthly recurring plans</span><strong>{pricingPlans.length}</strong></div></aside></section><section className="section-pad card-grid three-grid">{pillars.map((feature) => <Card className="feature-card" key={feature}><span className="card-icon">⚡</span><h3>{feature}</h3><p>Reusable app structure, forms, mock data, and backend-ready workflows designed for premium soccer organizations.</p></Card>)}</section><section className="section-pad"><div className="page-hero"><p className="eyebrow">Role-based SaaS for soccer</p><h2>One operating system, five focused experiences.</h2></div><div className="card-grid four-grid">{roles.map((role) => <Card key={role}><h3>{role} Dashboard</h3><p>{role}s get purpose-built metrics, actions, and forms for their part of the development and recruiting journey.</p></Card>)}</div></section><section className="section-pad split-section"><Card><p className="eyebrow">Scalable data model</p><h2>Backend-ready architecture</h2><div className="schema-grid">{Object.entries(dataModel).map(([name, fields]) => <div key={name}><strong>{name}</strong><small>{fields.slice(0, 4).join(', ')}…</small></div>)}</div></Card><Card className="dark-card"><p className="eyebrow">MVP workflow</p><h2>Profile → Plan → Train → Recruit → Report</h2><p>Every page is connected with polished placeholder data and ready to accept real backend APIs later.</p><Button to="/login">Open dashboard</Button></Card></section><section className="cta section-pad"><h2>Turn player development into a clear, measurable, college-ready pathway.</h2><Button to="/register">Start with ProHub</Button></section></main><Footer /></>;
}
