import Header from '../../components/layout/Header.jsx';
import Footer from '../../components/layout/Footer.jsx';
import Button from '../../components/ui/Button.jsx';
import Card from '../../components/ui/Card.jsx';
const features = ['Player Development Plans', 'Training Calendar', 'College Recruiting Tracker', 'Coach Feedback', 'Player Journal', 'Club Dashboards'];
const roles = ['Players', 'Parents', 'Coaches', 'Directors', 'Recruiters'];
export default function Home() {
  return <><Header /><main><section className="hero section-pad"><div className="hero-content"><p className="eyebrow">PISA ProHub SaaS Platform</p><h1>The Complete Soccer Development Hub for Players, Coaches, and Clubs</h1><p className="hero-copy">Track development, manage training, support recruiting, and connect every part of the player journey in one platform.</p><div className="hero-actions"><Button to="/login">Start Building My Profile</Button><Button to="/programs" variant="secondary">Explore ProHub</Button></div></div><aside className="hero-panel card glow-card"><div className="metric-row"><span>Active IDPs</span><strong>248</strong></div><div className="metric-row"><span>Training Journals</span><strong>1,842</strong></div><div className="metric-row"><span>Recruiting Profiles</span><strong>76</strong></div></aside></section><section className="section-pad card-grid three-grid">{features.map((feature) => <Card className="feature-card" key={feature}><span className="card-icon">⚡</span><h3>{feature}</h3><p>Connected workflows for Possession with Purpose to Attack, position-specific development, and clear progress evidence.</p></Card>)}</section><section className="section-pad"><h2>Built for every role in the pathway</h2><div className="card-grid five-grid">{roles.map((role) => <Card key={role}><h3>{role}</h3><p>Purpose-built tools, dashboards, and next actions for {role.toLowerCase()}.</p></Card>)}</div></section><section className="section-pad split-section"><Card><h2>How it works</h2>{['Create your profile', 'Build your development plan', 'Track training and feedback', 'Prepare for the next level'].map((step, index) => <div className="timeline-item" key={step}><span>{index + 1}</span><strong>{step}</strong></div>)}</Card><Card className="dark-card"><h2>Pricing preview</h2><p>Player, Coach, and Club plans scale from individual development to club-wide oversight.</p><Button to="/pricing">View pricing</Button></Card></section><section className="cta section-pad"><h2>Build the complete player development pathway with PISA ProHub.</h2><Button to="/login">Get started</Button></section></main><Footer /></>;
}
