import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { roles } from '../../data/mockUsers.js';
export default function Login() {
  const [role, setRole] = useState('coach');
  const navigate = useNavigate();
  const selected = roles.find((item) => item.id === role) || roles[0];
  return <main className="auth-page"><section className="auth-brand card"><div className="brand-row"><span className="brand-mark">⚡</span><div><h1>PISA PROHUB</h1><p>Every touch has a purpose.</p></div></div><h2>Build. Train. Perform.</h2><p>Your all-in-one platform for player development, coaching, recruiting, and performance.</p><div className="tag-list"><span>Sessions & Diagrams</span><span>Periodization</span><span>IDPs</span><span>Player Journals</span><span>Game Review</span></div><div className="auth-stats"><div><strong>One login</strong><span>All your tools</span></div><div><strong>Coach + Player</strong><span>Built for both</span></div><div><strong>Secure</strong><span>Backend-ready</span></div></div></section><section className="auth-form card"><h2>{selected.label === 'Coach' ? 'Coach with purpose' : `${selected.label} access`}</h2><p>Plan sessions, manage teams, and develop players — all in one place.</p><div className="segmented">{roles.slice(0,5).map((item)=><button key={item.id} className={role===item.id?'active':''} type="button" onClick={()=>setRole(item.id)}>{item.label.replace('/Admin','')}</button>)}</div><form onSubmit={(e)=>{e.preventDefault(); navigate(selected.path);}}><label>Email address<input type="email" placeholder="you@domain.com" required /></label><label>Password<input type="password" placeholder="••••••••" required /></label><div className="form-row"><label className="check"><input type="checkbox" /> Remember me</label><Link to="/forgot-password">Forgot your password?</Link></div><button className="btn btn-primary full" type="submit">Log in</button><Link className="btn btn-secondary full" to="/register">New to ProHub? Create an account</Link></form></section></main>;
}
