import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { roles } from '../../data/pisaData.js';
export default function Login() {
  const [role, setRole] = useState('player');
  const navigate = useNavigate();
  const selected = roles.find((item) => item.id === role) || roles[0];
  return <main className="auth-page"><section className="auth-brand card"><div className="brand-row"><span className="brand-mark">P</span><div><h1>PISA OS</h1><p>AI-powered soccer development and college recruiting.</p></div></div><h2>Train smarter. Recruit clearer.</h2><p>Choose a role to preview a working dashboard with forms, mock AI generation, reports, and Stripe-ready plan selection.</p><div className="tag-list"><span>Profiles</span><span>IDPs</span><span>Training</span><span>Recruiting CRM</span><span>Reports</span></div><div className="auth-stats"><div><strong>4 roles</strong><span>Player, parent, coach, admin</span></div><div><strong>AI-ready</strong><span>OpenAI can be added later</span></div><div><strong>Stripe-ready</strong><span>Subscriptions + one-time</span></div></div></section><section className="auth-form card"><p className="eyebrow">{selected.label} login</p><h2>{selected.description}</h2><div className="segmented">{roles.map((item)=><button key={item.id} className={role===item.id?'active':''} type="button" onClick={()=>setRole(item.id)}>{item.label}</button>)}</div><form onSubmit={(e)=>{e.preventDefault(); navigate(selected.path);}}><label>Email address<input type="email" placeholder="you@pisaos.com" required /></label><label>Password<input type="password" placeholder="••••••••" required /></label><div className="form-row"><label className="check"><input type="checkbox" /> Remember me</label><Link to="/forgot-password">Forgot password?</Link></div><button className="btn btn-primary full" type="submit">Log in as {selected.label}</button><Link className="btn btn-secondary full" to="/register">Create account</Link></form></section></main>;
}
